import Image from "next/image";
import { Inter } from "next/font/google";
import Layout from "@/src/components/Layout";
import profilePic from "../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/src/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/src/components/Icons";
import HireMe from "@/src/components/HireMe";
import lightIcon from "../public/images/svgs/miscellaneous_icons_1.svg";
import profilePic2 from "../public/images/profile/developer-profile-img-removebg.png";
import Head from "next/head";
import TransitionEffect from "@/src/components/TransitionEffect";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
    <Head>
      <title>Create next App</title>
      <meta name="description" content="generated by create next app"/>
    </Head>
    <TransitionEffect/>
    <main
      className={`flex min-h-screen w-full text-dark flex-col items-center justify-between ${inter.className}`}
    >
      <Layout>
        <div className="flex lg:flex-col lg:p-6 sm:p-4">
          <div className="w-1/2 sm:w-full md:w-full mx-auto lg:hidden sm:block">
            {" "}
            <Image
              src={profilePic2}
              alt="CodeBucks"
              className="w-10/12 h-auto"
              priority
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
            />
          </div>
          <div className="w-1/2 lg:w-full sm:w-full flex flex-col items-center self-center sm:mt-5">
            <AnimatedText
              text="Turning Vision Into Reality With Code And Design."
              className="!text-5xl !text-left md:!text-5xl sm:!text-4xl md:text-center sm:text-center"
            />
            <p className="my-4 text-base font-medium sm:text-sm">
              As a skilled full-stack developer, I am dedicated to turning ideas
              into innovative web applications. Explore my latest projects and
              articles, showcasing my expertise in React.js and web development.
            </p>
            <div className="flex items-center self-start mt-2 sm:self-center md:self-center">
              <Link
                href={"/dummy.pdf"}
                target="_blank"
                className="dark:bg-light dark:text-dark hover:dark:border-light hover:dark:bg-dark hover:dark:text-light flex items-center bg-dark text-light p-2 px-4 rounded-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark"
                download={true}
              >
                Resume <LinkArrow className={"w-6 ml-1"} />{" "}
              </Link>
              <Link
                href={"mailto:habibsujan007@gmail.com"}
                className="px-4 underline"
              >
                Contact
              </Link>
            </div>
          </div>
        </div>
      </Layout>
      <HireMe />
      <div className="absolute right-8 -bottom-36 inline-block w-24 lg:hidden ">
        <Image className="w-full h-auto" src={lightIcon} alt="CodeBucks" />
      </div>
    </main>
    </>
  );
}
